using System;
using System.Collections.Generic;
using Reefin.Model.Dlna;
using Reefin.Model.Dto;

namespace Reefin.Model.MediaInfo
{
    /// <summary>
    /// Class PlaybackInfoResponse.
    /// </summary>
    public class PlaybackInfoResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaybackInfoResponse" /> class.
        /// </summary>
        public PlaybackInfoResponse()
        {
            MediaSources = Array.Empty<MediaSourceInfo>();
        }

        /// <summary>
        /// Gets or sets the media sources.
        /// </summary>
        /// <value>The media sources.</value>
        public IReadOnlyList<MediaSourceInfo> MediaSources { get; set; }

        /// <summary>
        /// Gets or sets the play session identifier.
        /// </summary>
        /// <value>The play session identifier.</value>
        public string? PlaySessionId { get; set; }

        /// <summary>
        /// Gets or sets the error code.
        /// </summary>
        /// <value>The error code.</value>
        public PlaybackErrorCode? ErrorCode { get; set; }

        /// <summary>
        /// Gets or sets the opaque, client-supplied playback attempt id (issue #43), echoed back
        /// verbatim, or <c>null</c> when the client supplied none.
        /// </summary>
        /// <remarks>
        /// Distinct from <see cref="PlaySessionId"/> in scope: the attempt id is generated by the
        /// client BEFORE any session exists and stays identical across every request of the attempt
        /// - retries and a subsequent <c>POST Playback/Sessions</c> included - whereas
        /// <see cref="PlaySessionId"/> is per session and can outlive several attempts. Echoed
        /// rather than regenerated: the server never mints this value and imposes no structure on
        /// it.
        /// </remarks>
        /// <value>The playback attempt identifier.</value>
        public string? PlaybackAttemptId { get; set; }
    }
}
