#!/usr/bin/env bash
# Make Python on Windows write LF, for scripts this work may not edit (W1-A2 / #236).
#
# Python on Windows translates '\n' to '\r\n' on text stdout. Every shell that
# captures Python output then gets a carriage return glued to the last field,
# because `$(...)` strips trailing NEWLINES and leaves the CR in front of them.
#
# W1-A2's own scripts strip it where they read Python. ci/ffmpeg/fetch-sources.sh
# cannot: it belongs to the Linux runtimes, where the behaviour does not exist,
# and this work is required to leave it byte-identical. Its component table puts
# the mirror list last, so on Windows the last mirror of every component arrives
# as "https://…tar.xz<CR>" and curl answers
#
#     curl: (3) URL rejected: Malformed input to a URL function
#
# That is invisible until a primary URL fails. www.freedesktop.org rate-limits
# shared CI address space with HTTP 418 — a permanent condition of hosted builds,
# not a freak event — so the fontconfig mirror is reached on a normal run, and
# the whole fetch then fails with every source exhausted.
#
# The fix is a shim, not an edit: a `python3` earlier on PATH that filters its
# own stdout. The Linux-owned script then behaves on Windows exactly as it does
# on Linux, and keeps its bytes.
#
# Usage: install-python-shim.sh [dir]   (default /c/tf-shims)

set -euo pipefail

DIR="${1:-/c/tf-shims}"
mkdir -p "${DIR}"

real="$(command -v python3 || command -v python || true)"
[[ -n "${real}" ]] || { echo "no python on PATH to wrap" >&2; exit 1; }
# Resolve now, so the shim cannot find itself once DIR is on PATH.
case "${real}" in
    "${DIR}"/*) echo "refusing to wrap the shim itself: ${real}" >&2; exit 1 ;;
esac

for name in python3 python; do
    cat > "${DIR}/${name}" <<EOF
#!/usr/bin/env bash
# Generated by ci/windows/ffmpeg/install-python-shim.sh (W1-A2, #236).
# Streams through tr rather than capturing: a capture would buffer the output of
# a long fetch and swallow its trailing newline. PIPESTATUS keeps the real exit
# code, which a bare pipeline would replace with tr's.
"${real}" "\$@" | tr -d '\r'
exit "\${PIPESTATUS[0]}"
EOF
    chmod 0755 "${DIR}/${name}"
done

# Prove it before anything depends on it. A shim that silently did nothing would
# leave exactly the failure it exists to prevent.
probe="$(PATH="${DIR}:${PATH}" python3 -c 'print("a"); print("b")' | od -An -c | tr -s ' ')"
case "${probe}" in
    *'\r'*) echo "the shim did not remove the carriage return: ${probe}" >&2; exit 1 ;;
esac
echo "python shim installed in ${DIR}, wrapping ${real}"
