<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Tesserafin Contributors</Authors>
    <PackageId>Tesserafin.MediaEncoding.Keyframes</PackageId>
    <VersionPrefix>10.11.0</VersionPrefix>
    <RepositoryUrl>https://github.com/tesserafin/tesserafin</RepositoryUrl>
    <PackageLicenseExpression>GPL-2.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Stability)'=='Unstable'">
    <!-- Include all symbols in the main nupkg until Azure Artifact Feed starts supporting ingesting NuGet symbol packages. -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NEbml" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Tesserafin.MediaEncoding.Keyframes.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
