#!/usr/bin/env bash
# PR115d — OPTIONAL smoke stage. NOT part of the mandatory merge gate (ci/run.sh runs the full suite
# with `--filter 'Category!=Smoke'`, which excludes everything this script runs).
#
# WHAT THIS PROVES, PRECISELY — read this before trusting a green run:
#
#   1. ffmpeg/HLS mechanics work in this Docker image (Dockerfile.ci already installs ffmpeg for the
#      main build/test gate). A real ffmpeg process, run through
#      Reefin.MediaEncoding.Encoder.FfmpegProcessRunner — the same production process-running
#      component TranscodeManager.StartFfMpeg uses — synthesizes a tiny testsrc+sine lavfi source (no
#      test media asset needed) and produces a real HLS manifest (.m3u8) plus at least one real,
#      non-empty segment (.ts). tests/Reefin.MediaEncoding.Tests/Encoder/HlsSmokeTests.cs.
#
#   2. The v2/legacy serve-or-fallback DECISION and the admin diagnostics endpoint are correct, end to
#      end against the real MediaInfoHelper/PlaybackSessionManager/PlaybackStopThresholdGuard wiring
#      (mocked only at the I/O boundary — user manager, config manager, execution plan resolver):
#      legacy mode, canary/V2 mode, the kill switch, the Dolby Vision exclusion, an adapter exception,
#      and the PR115d stop-threshold guard all forcing the correct typed fallback reason — plus that
#      GET /System/PlaybackDiagnostics/Metrics reflects whatever was recorded.
#      tests/Reefin.Api.Tests/Helpers/MediaInfoHelperLiveWiringTests.cs,
#      tests/Reefin.Api.Tests/Controllers/PlaybackDiagnosticsMetricsControllerTests.cs.
#
# WHAT THIS DOES NOT PROVE, AND WHY — a genuine attempt at more was made and abandoned for a concrete,
# documented reason, not skipped for convenience:
#
#   That a real HTTP client, hitting a REAL BOOTED Reefin server's playback endpoint, receives bytes
#   generated by the ACTUAL ffmpeg command line the v2/legacy decision above would produce for that
#   exact request. Proving that requires: an admin account provisioned through the setup wizard, a
#   scanned library containing a real (or synthesized) media item, a real auth token, and
#   DynamicHlsController actually invoked over HTTP with EncodingHelper's real argument-building for
#   that item. This repository's only existing full-server test harness,
#   tests/Reefin.Server.Integration.Tests/ReefinApplicationFactory.cs, explicitly sets
#   REEFIN_FFMPEG__NOVALIDATION=true and is used by zero existing tests that create a library, add a
#   real media item, or drive DynamicHlsController/MediaInfoController's playback routes — that
#   scaffolding does not exist anywhere in this repo today. Building it from scratch (setup-wizard
#   timing, library-scan-completion polling, auth-token acquisition, hardware-encoder availability
#   inside a container) was judged, after this concrete investigation, too large and too flaky to add
#   reliably within PR115d's scope. This gap is real; (1)+(2) above do not close it together, only
#   separately narrow it (real ffmpeg mechanics; real decision routing) — see
#   docs/pr115d-rollout-runbook.md §7 for the same statement in the rollout runbook.
#
# Usage:
#   ./ci/smoke.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

IMAGE_TAG="reefin-ci"
NUGET_VOLUME="reefin-nuget"
SOLUTION="Reefin.sln"
SMOKE_FILTER="Category=Smoke|FullyQualifiedName~MediaInfoHelperLiveWiringTests|FullyQualifiedName~PlaybackDiagnosticsMetricsControllerTests"

banner() {
    echo ""
    echo "======================================================================"
    echo "== $*"
    echo "======================================================================"
}

START_TS=$(date +%s)

banner "Building ${IMAGE_TAG} from Dockerfile.ci (same image as ci/run.sh)"
BUILD_CTX="$(mktemp -d)"
trap 'rm -rf "$BUILD_CTX"' EXIT
docker build -f Dockerfile.ci -t "$IMAGE_TAG" "$BUILD_CTX"

banner "dotnet build + PR115d smoke-scoped dotnet test inside container"
set +e
docker run --rm \
    -v "$PWD":/repo \
    -v "${NUGET_VOLUME}":/nuget \
    -w /repo \
    "$IMAGE_TAG" \
    bash -c "
        set -euo pipefail
        echo '-- dotnet restore --'
        dotnet restore '${SOLUTION}'
        echo '-- dotnet build (fail fast on errors) --'
        dotnet build '${SOLUTION}' --no-restore -clp:ErrorsOnly
        echo '-- dotnet test (PR115d smoke scope: HlsSmokeTests + live-wiring decision + diagnostics endpoint) --'
        dotnet test '${SOLUTION}' --no-build --nologo --filter '${SMOKE_FILTER}'
    "
STATUS=$?
set -e

banner "Restoring working tree ownership to $(id -u):$(id -g)"
docker run --rm -v "$PWD":/repo "$IMAGE_TAG" chown -R "$(id -u):$(id -g)" /repo || true

END_TS=$(date +%s)
ELAPSED=$((END_TS - START_TS))

banner "SUMMARY"
if [ "$STATUS" -eq 0 ]; then
    echo "RESULT: PASS — ffmpeg/HLS synthesis + v2/legacy decision routing + diagnostics endpoint, all green in Docker (${ELAPSED}s wall time)"
    echo "Reminder: this does NOT prove a real booted server serves real HLS bytes to a real client for a real media item — see this script's header."
else
    echo "RESULT: FAIL — see the first failing stage above (dotnet restore/build/test) (${ELAPSED}s wall time)" >&2
fi

exit "$STATUS"
