#!/usr/bin/env bash
# PR115d — OPTIONAL smoke stage. NOT part of the mandatory merge gate (ci/run.sh runs the full suite
# with `--filter 'Category!=Smoke'`, which excludes everything this script runs).
#
# WHAT THIS PROVES, PRECISELY — read this before trusting a green run:
#
#   1. ffmpeg/HLS mechanics work in this Docker image (Dockerfile.ci already installs ffmpeg for the
#      main build/test gate). A real ffmpeg process, run through
#      Tesserafin.MediaEncoding.Encoder.FfmpegProcessRunner — the same production process-running
#      component TranscodeManager.StartFfMpeg uses — synthesizes a tiny testsrc+sine lavfi source (no
#      test media asset needed) and produces a real HLS manifest (.m3u8) plus at least one real,
#      non-empty segment (.ts). tests/Tesserafin.MediaEncoding.Tests/Encoder/HlsSmokeTests.cs.
#
#   2. The v2/legacy serve-or-fallback DECISION and the admin diagnostics endpoint are correct, end to
#      end against the real MediaInfoHelper/PlaybackSessionManager/PlaybackStopThresholdGuard wiring
#      (mocked only at the I/O boundary — user manager, config manager, execution plan resolver):
#      legacy mode, canary/V2 mode, the kill switch, the Dolby Vision exclusion, an adapter exception,
#      and the PR115d stop-threshold guard all forcing the correct typed fallback reason — plus that
#      GET /System/PlaybackDiagnostics/Metrics reflects whatever was recorded.
#      tests/Tesserafin.Api.Tests/Helpers/MediaInfoHelperLiveWiringTests.cs,
#      tests/Tesserafin.Api.Tests/Controllers/PlaybackDiagnosticsMetricsControllerTests.cs.
#
# WHAT THIS DOES NOT PROVE, AND WHY — a genuine attempt at more was made and abandoned for a concrete,
# documented reason at the time, not skipped for convenience:
#
#   That a real HTTP client, hitting a REAL BOOTED Reefin server's playback endpoint, receives bytes
#   generated by the ACTUAL ffmpeg command line the v2/legacy decision above would produce for that
#   exact request. This repository's only full-server test harness at the time,
#   tests/Tesserafin.Server.Integration.Tests/TesserafinApplicationFactory.cs, explicitly set
#   REEFIN_FFMPEG__NOVALIDATION=true and was used by zero tests that created a library, added a real
#   media item, or drove DynamicHlsController/MediaInfoController's playback routes — that scaffolding
#   did not exist anywhere in this repo at PR115d's time. Building it from scratch (setup-wizard
#   timing, auth-token acquisition, a real ffmpeg-wired host, a real library item) was judged, after a
#   concrete investigation, too large for PR115d's scope.
#
#   PR119 closed this gap: see ./ci/smoke-e2e.sh (called below), which drives exactly this — a real
#   booted server (its own E2eApplicationFactory, wired to a real ffmpeg/ffprobe binary, unlike this
#   script's own dotnet test run below), a real seeded library item, and a real HTTP client fetching
#   the URL GET Playback/Sessions/{id}/Stream names, for DirectPlay/remux/transcode-HLS/external-
#   subtitle/kill-switch-fallback. Kept in its own script rather than folded into the filter below:
#   it is meaningfully heavier (a real ffmpeg encode for the transcode scenario) than everything else
#   this script runs, so its own timing/pass-fail is reported separately.
#
# Usage:
#   ./ci/smoke.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

IMAGE_TAG="reefin-ci"
NUGET_VOLUME="reefin-nuget"
SOLUTION="Tesserafin.sln"
# PR119: PlaybackUrlContractEndToEndTests is Category=Smoke too (so ci/run.sh still excludes it) but is
# deliberately carved out of this filter - it runs via ci/smoke-e2e.sh below instead, as its own
# separately-timed stage.
SMOKE_FILTER="(Category=Smoke|FullyQualifiedName~MediaInfoHelperLiveWiringTests|FullyQualifiedName~PlaybackDiagnosticsMetricsControllerTests)&FullyQualifiedName!~PlaybackUrlContractEndToEndTests"

banner() {
    echo ""
    echo "======================================================================"
    echo "== $*"
    echo "======================================================================"
}

START_TS=$(date +%s)

banner "Building ${IMAGE_TAG} from Dockerfile.ci (same image as ci/run.sh)"
BUILD_CTX="$(mktemp -d)"
trap 'rm -rf "$BUILD_CTX"' EXIT
docker build -f Dockerfile.ci -t "$IMAGE_TAG" "$BUILD_CTX"

banner "dotnet build + PR115d smoke-scoped dotnet test inside container"
set +e
docker run --rm \
    -v "$PWD":/repo \
    -v "${NUGET_VOLUME}":/nuget \
    -w /repo \
    "$IMAGE_TAG" \
    bash -c "
        set -euo pipefail
        echo '-- dotnet restore --'
        dotnet restore '${SOLUTION}'
        echo '-- dotnet build (fail fast on errors) --'
        dotnet build '${SOLUTION}' --no-restore -clp:ErrorsOnly
        echo '-- dotnet test (PR115d smoke scope: HlsSmokeTests + live-wiring decision + diagnostics endpoint) --'
        dotnet test '${SOLUTION}' --no-build --nologo --filter '${SMOKE_FILTER}'
    "
STATUS=$?
set -e

banner "Restoring working tree ownership to $(id -u):$(id -g)"
docker run --rm -v "$PWD":/repo "$IMAGE_TAG" chown -R "$(id -u):$(id -g)" /repo || true

END_TS=$(date +%s)
ELAPSED=$((END_TS - START_TS))

banner "SUMMARY (this script's own stage)"
if [ "$STATUS" -eq 0 ]; then
    echo "RESULT: PASS — ffmpeg/HLS synthesis + v2/legacy decision routing + diagnostics endpoint, all green in Docker (${ELAPSED}s wall time)"
else
    echo "RESULT: FAIL — see the first failing stage above (dotnet restore/build/test) (${ELAPSED}s wall time)" >&2
fi

# PR119: the real-booted-server/real-HTTP-client proof this script's header used to name as an open
# gap - its own script (separately timed: a real ffmpeg encode makes it meaningfully heavier than
# everything above).
banner "Calling ci/smoke-e2e.sh (PR119 end-to-end URL contract proof)"
set +e
"$REPO_ROOT/ci/smoke-e2e.sh"
E2E_STATUS=$?
set -e

if [ "$STATUS" -eq 0 ] && [ "$E2E_STATUS" -eq 0 ]; then
    exit 0
fi

exit 1
