<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\SharedVersion.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Reefin.Common\Reefin.Common.csproj" />
    <ProjectReference Include="..\..\Reefin.Controller\Reefin.Controller.csproj" />
  </ItemGroup>

</Project>
